### ISSUE TITLE
Does not install with next 11 using npm  

### ISSUE THREAD

**Issue by Klin-Coders** [NiklasMencke/nextjs-breadcrumbs#12]
I get this error when i install with next v11

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web@0.1.0
npm ERR! Found: next@11.0.0
npm ERR! node_modules/next
npm ERR!   next@"^11.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^10.0.0" from nextjs-breadcrumbs@1.1.3
npm ERR! node_modules/nextjs-breadcrumbs
npm ERR!   nextjs-breadcrumbs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by NiklasMencke** [comment]
Thanks! 

Fixed in https://github.com/NiklasMencke/nextjs-breadcrumbs/pull/16
