### ISSUE TITLE
Add ability to omit rootlabel, or replace it with icon

### ISSUE THREAD

**Issue by 10000multiplier** [NiklasMencke/nextjs-breadcrumbs#14]
i have a page on my website as follows:

https://website.com/home

now the breadcrumbs shows /home/home

**Comment by NiklasMencke** [comment]
Great find! Will tackle it soon.

**Comment by NiklasMencke** [comment]
Added boolean flag in https://github.com/NiklasMencke/nextjs-breadcrumbs/pull/17

For the Icon feature feel free to create a PR :)
