### ISSUE TITLE
transformLabel?: ((title: string) => React.ReactNode) | undefined;

### ISSUE THREAD

**Issue by albertcito** [NiklasMencke/nextjs-breadcrumbs#18]
Could be possible add modify:

`transformLabel?: ((title: string) => string) | undefined;` 
to 
`transformLabel?: ((title: string) => React.ReactNode) | undefined;`

Because I would like replace `Home` by an icon.

```typescript
transformLabel={(label: string) => {
  if (label === 'Home') {
    return <HomeOutlined />;
  }
  return label;
}}
```

**Comment by NiklasMencke** [comment]
Good catch! Fixed in https://github.com/NiklasMencke/nextjs-breadcrumbs/pull/21
