### ISSUE TITLE
Dont display query values

### ISSUE THREAD

**Issue by albertcito** [NiklasMencke/nextjs-breadcrumbs#19]
I have this URL: 
-  `http://localhost:3001/login?redirect=aHR0cDovL2xvY2FsaG9zdDozMDAxLw==`

And breadcrumb display it:
- `Home / Login?Redirect=AHR0cDovL2xvY2FsaG9zdDozMDAxLw==`

**Comment by NiklasMencke** [comment]
fixed. thank you!
