### ISSUE TITLE
Issue with utf-8 characters

### ISSUE THREAD

**Issue by coditori** [NiklasMencke/nextjs-breadcrumbs#2]
Hi, if you have URL path like [this](https://www.bahabin.com/currencies/%D8%AF%D9%84%D8%A7%D8%B1%20%D8%A2%D8%B2%D8%A7%D8%AF%20%D8%AA%D9%87%D8%B1%D8%A7%D9%86)  then characters won't show up correctly.

**Comment by NiklasMencke** [comment]
Fixed in https://github.com/NiklasMencke/nextjs-breadcrumbs/pull/23
