### ISSUE TITLE
Adding features to omit specific via passing path name or path index. 

### ISSUE THREAD

**Issue by sagargg** [NiklasMencke/nextjs-breadcrumbs#22]
Sometimes not all paths are needed to display eg. I don't want to display pagination path params.  In that case, it can be very useful to remove a specific path from the breadcrumbs with a omit feature.

**Comment by NiklasMencke** [comment]
Good idea for specific use cases. I implemented the feature in https://github.com/NiklasMencke/nextjs-breadcrumbs/pull/29

`const Example = () => {
  return <Breadcrumbs useDefaultStyle={true} omitIndexList={[1]} />;
};`
