### ISSUE TITLE
.prettierrc is conflict with .eslint

### ISSUE THREAD

**Issue by nemu626** [NiklasMencke/nextjs-breadcrumbs#6]
https://github.com/NiklasMencke/nextjs-breadcrumbs/blob/73640ceca0f24fc1163534bec4f0d8739dfd538d/.prettierrc#L1-L10

https://github.com/NiklasMencke/nextjs-breadcrumbs/blob/73640ceca0f24fc1163534bec4f0d8739dfd538d/.eslintrc#L43-L58

`semi` , `jsxBracketSameLine` props are not equal. 
So, in my VScode, `eslint autofix` insert semicolons, but `prettier`(run at save file) remove that.
 I think it must be same value

**Comment by NiklasMencke** [comment]
Thank you!

fixed in https://github.com/NiklasMencke/nextjs-breadcrumbs/pull/15
